### ISSUE TITLE
Corrigir responsividade do pop-up quando o usuário não está logado na tela de 'Find Connections'

### ISSUE THREAD

**Issue by laurascotelari** [Pontes-de-Geracoes/front-end#43]
![Image](https://github.com/user-attachments/assets/768bb2bf-fe2e-4789-8614-402e1797a538)

**Comment by laurascotelari** [comment]
Notei que o tamanho do pop-up não está mais acompanhando o texto:

![image](https://github.com/user-attachments/assets/70d873d7-c5b6-4c33-a2c6-3ace689088e1)

**Comment by laurascotelari** [comment]
O card de novo encontro também está quebrado:

![image](https://github.com/user-attachments/assets/297815ad-efa5-4d83-9f94-54dd63052d28)

**Comment by Caulicons** [comment]
@laurascotelari  Você quer que eu dê uma atenção nessa parte ?

**Comment by Caulicons** [comment]
Eu tinha resolvido ontem, uma parte desse error, você fez o pull ? 

> O card de novo encontro também está quebrado:
> 
> ![image](https://github.com/user-attachments/assets/297815ad-efa5-4d83-9f94-54dd63052d28)

**Comment by Caulicons** [comment]
Vou adiantar essas partes
